#!/usr/bin/env python3
"""List production-selected (PROD_*) XNNPACK microkernels for x86 and wasm.

"Selected in production" means a kernel source file that appears in a
``PROD_<ISA>_MICROKERNEL_SRCS`` list inside ``gen/<isa>_microkernels.bzl``
(the ``NON_PROD_*`` lists hold every other registered kernel). Those ``.bzl``
files are auto-generated by ``tools/update-microkernels.py``.

This tool parses those PROD lists, keeps only the x86 and wasm ISAs, and emits
one row per PROD kernel with the fields needed to pair f32 against f16 and to
build a Google Benchmark ``--benchmark_filter`` that runs only PROD kernels.

Two output modes:
  * ``list``   (default) -- CSV of every PROD x86/wasm kernel.
  * ``filter`` -- print the ``--benchmark_filter`` regex for one op+precision,
                  used by ``scripts/bench-compare-f16-f32-prod.sh``.
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path

# ISA .bzl stems we care about. Everything else (neon*, rvv*, hvx, sse-only
# legacy, etc.) is intentionally excluded per the x86 + wasm scope.
X86_ISAS = (
    "avx2",
    "fma3",
    "f16c",
    "avx512f",
    "avx512fp16",
    "avx512skx",
    "avxvnni",
)
WASM_ISAS = (
    "wasmsimd",
    "wasmrelaxedsimd",
)

# Maps the benchmark "op" name (as used by the runner / summarizer) to the
# source-family token that appears in the .bzl path ``src/f{16,32}-<family>/``.
# ``gemm`` and ``gemm_minmax`` share the same source family (the ``-minmax-``
# marker lives in the filename, not the directory).
OP_TO_FAMILY = {
    "gemm": "gemm",
    "gemm_minmax": "gemm",
    "igemm": "igemm",
    "dwconv": "dwconv",
    "dwconv2d_chw": "dwconv2d-chw",
    "conv_hwc2chw": "conv-hwc2chw",
    "raddstoreexpminusmax": "raddstoreexpminusmax",
    "vcmul": "vcmul",
}

# Order matters: 512-bit must be checked before the 256-bit tokens because
# ``avx256`` contains ``avx2`` and ``avx512f`` contains ``avx``.
_GENERATION_RULES = (
    ("avx512", "avx512"),
    ("avx256", "avx2"),
    ("avxvnni", "avx2"),
    ("avx2", "avx2"),
    ("fma3", "avx2"),
    ("avx", "avx2"),
    ("wasmrelaxedsimd", "wasmsimd"),
    ("wasmsimd", "wasmsimd"),
    ("sse", "sse"),
)


def isa_generation(isa: str) -> str:
    s = isa.lower()
    for needle, gen in _GENERATION_RULES:
        if needle in s:
            return gen
    return "other"


# A kernel source stem looks like one of:
#   f16-gemm-1x32-minmax-avx512fp16-broadcast
#   f32-gemm-1x16s4-minmax-fma3-broadcast
#   f16-dwconv-25p8c-minmax-fma3-acc2
#   f16-vadd-avx512fp16-u64                (no tile, no -minmax-)
# We split into: precision, family, tile (optional), isa, variant (optional).
_ISA_ALTERNATION = "|".join(
    sorted(set(X86_ISAS) | set(WASM_ISAS), key=len, reverse=True)
)
_STEM_RE = re.compile(
    r"^f(?P<prec>16|32)-(?P<family>[a-z0-9]+(?:-[a-z0-9]+)*?)"
    r"(?:-(?P<tile>\d+[a-z0-9]*))?"
    r"(?:-minmax)?"
    r"-(?P<isa>" + _ISA_ALTERNATION + r")"
    r"(?:-(?P<variant>[a-z0-9-]+))?$"
)


def parse_prod_block(bzl_path: Path) -> list[str]:
    """Return the source paths inside every ``PROD_*`` list in a .bzl file."""
    srcs: list[str] = []
    inside = False
    for line in bzl_path.read_text().splitlines():
        stripped = line.strip()
        if stripped.startswith("PROD_") and stripped.endswith("= ["):
            inside = True
            continue
        if stripped.startswith("NON_PROD_"):
            inside = False
            continue
        if inside:
            if stripped == "]":
                inside = False
                continue
            m = re.search(r'"([^"]+)"', stripped)
            if m:
                srcs.append(m.group(1))
    return srcs


def stem_of(src_path: str) -> str:
    return Path(src_path).stem


def parse_stem(stem: str) -> dict | None:
    m = _STEM_RE.match(stem)
    if not m:
        return None
    d = m.groupdict()
    d["tile"] = d["tile"] or ""
    d["variant"] = d["variant"] or ""
    return d


def filter_fragment(tile: str, isa: str) -> str:
    """Build the invariant substring that selects this PROD kernel by name.

    Verified against real binaries: the Google Benchmark test name embeds
    ``_{tile}__{isa}...`` (e.g. ``_1x32__avx512fp16_broadcast``). We append
    ``(_|/)`` after the ISA so ``avx512f`` never matches ``avx512fp16`` and so
    tile-less kernels (``__{isa}/``) still match.
    """
    isa_re = re.escape(isa)
    if tile:
        return rf"_{re.escape(tile)}__{isa_re}(_|/)"
    return rf"__{isa_re}(_|/)"


def collect(gen_dir: Path, isas: tuple[str, ...]) -> list[dict]:
    rows: list[dict] = []
    for isa_file in isas:
        bzl = gen_dir / f"{isa_file}_microkernels.bzl"
        if not bzl.exists():
            continue
        for src in parse_prod_block(bzl):
            stem = stem_of(src)
            parsed = parse_stem(stem)
            if parsed is None:
                continue
            rows.append(
                {
                    "isa_file": isa_file,
                    "precision": f"f{parsed['prec']}",
                    "family": parsed["family"],
                    "tile": parsed["tile"],
                    "isa": parsed["isa"],
                    "variant": parsed["variant"],
                    "gen": isa_generation(parsed["isa"]),
                    "source": src,
                    "filter_fragment": filter_fragment(parsed["tile"], parsed["isa"]),
                }
            )
    return rows


def backend_isas(backend: str) -> tuple[str, ...]:
    if backend == "x86":
        return X86_ISAS
    if backend == "wasm":
        return WASM_ISAS
    return X86_ISAS + WASM_ISAS


def cmd_list(args: argparse.Namespace) -> int:
    rows = collect(args.gen_dir, backend_isas(args.backend))
    rows.sort(key=lambda r: (r["family"], r["precision"], r["gen"], r["isa"], r["tile"]))
    fields = [
        "precision",
        "family",
        "tile",
        "gen",
        "isa",
        "variant",
        "isa_file",
        "filter_fragment",
        "source",
    ]
    writer = csv.DictWriter(sys.stdout, fieldnames=fields, extrasaction="ignore")
    writer.writeheader()
    for r in rows:
        writer.writerow(r)
    return 0


def cmd_filter(args: argparse.Namespace) -> int:
    family = OP_TO_FAMILY.get(args.op)
    if family is None:
        print(f"unknown op: {args.op}", file=sys.stderr)
        return 2
    rows = collect(args.gen_dir, backend_isas(args.backend))
    fragments: list[str] = []
    seen: set[str] = set()
    for r in rows:
        if r["family"] != family or r["precision"] != args.precision:
            continue
        frag = r["filter_fragment"]
        if frag not in seen:
            seen.add(frag)
            fragments.append(frag)
    # Empty output signals "no PROD kernels for this op+precision+backend";
    # the runner treats that as "skip".
    print("|".join(fragments))
    return 0


def parse_args(argv: list[str]) -> argparse.Namespace:
    repo_root = Path(__file__).resolve().parent.parent
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument(
        "--gen-dir",
        type=Path,
        default=repo_root / "gen",
        help="Directory holding <isa>_microkernels.bzl (default: <repo>/gen).",
    )
    p.add_argument(
        "--backend",
        choices=["x86", "wasm", "both"],
        default="both",
        help="Which ISA family to include (default: both).",
    )
    sub = p.add_subparsers(dest="command")

    p_list = sub.add_parser("list", help="Emit a CSV of PROD x86/wasm kernels.")
    p_list.set_defaults(func=cmd_list)

    p_filter = sub.add_parser("filter", help="Emit a --benchmark_filter regex for one op+precision.")
    p_filter.add_argument("--op", required=True, choices=sorted(OP_TO_FAMILY))
    p_filter.add_argument("--precision", required=True, choices=["f16", "f32"])
    p_filter.set_defaults(func=cmd_filter)

    args = p.parse_args(argv)
    if args.command is None:
        args.command = "list"
        args.func = cmd_list
    return args


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
